# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 135d853fab35666012c044c19e0a12a6929b5cc708b7b2219a76ab9c3a837f4df1034c17b9c60dd82e2e950344ccd0785c2dc88374c7e4dd991291228fa21f80

test:
  secret_key_base: 83d1ab41f25b2650927e63d8299d2b243d0b225f155aa33828b6d62d2b3c44d35634c9970de13822a74086069bd297332eaa3f3ab430b0055fb1ff7abc193430

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
